title: Control Fan Page
baseURL: /
params:
  header:
    title: Control
    tagline: Discover an unknown world.
    logo_img: images/logo.png
    bg_img: images/header-bg.jpg
    has_nav: true
  footer:
    content: 'Content courtesy of the [Control Wiki](https://control.fandom.com/wiki/Control_Wiki).'
    links:
      - text: Made with Sourcebit
        url: 'https://github.com/stackbithq/sourcebit'
        new_window: true
  palette: yellow
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
